language: elixir
elixir:
  - 1.7.1
  - 1.7.0
  - 1.6.6
  - 1.6.5
otp_release:
  - 21.0
  - 20.3
  - 20.1
  - 20.0
sudo: false
matrix:
  include:
    - install:
      - mix local.hex --force
      - mix archive.install hex bunt '~> 0.2' --force
      - mix archive.install hex credo '~> 0.9' --force
      script:
      - mix format --check-formatted --dry-run
      - mix credo