# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.0
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.7.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    environment:
      - MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, deps.compile
      - run: mix compile --warnings-as-errors --force
      - run: mix test # Elixir CircleCI 2.0 configuration file
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - steps:
          requires:
            - build
          filters:
            branches:
              only: master
